version: '3.9'
services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    hostname: traefik.server
    restart: always
    command:
      #- "--log.level=DEBUG"
      - "--api"
      - "--api.insecure=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=${TRAEFIK_EMAIL}"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.$DOMAIN_NAME`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.middlewares=traefik-auth, traefik-compress"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_USER}:${TRAEFIK_BASIC_PASSWORD_ENCODED}"
      - "traefik.http.middlewares.traefik-compress.compress=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/docker/traefik:/data"
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    restart: always
    labels:
      - "com.ouroboros.enable=true"
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - LABEL_ENABLE=true
      - LABELS_ONLY=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:13
    container_name: "postgres"
    hostname: pg.server
    restart: always
    environment:
      - "POSTGRES_DB=$DB_NAME"
      - "POSTGRES_USER=$DB_USER"
      - "POSTGRES_PASSWORD=$DB_PASS"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "/docker/postgres:/var/lib/postgresql/data"
  redis:
    image: redis
    container_name: "redis"
    hostname: redis.server
    restart: always
    command: [
        "redis-server",
        "--appendonly yes",
    ]
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "/docker/redis:/data"

  rediscommander:
    image: rediscommander/redis-commander:latest
    container_name: "rediscommander"
    hostname: rediscommander.server
    restart: always
    environment:
      - "REDIS_HOSTS=lvredis:redis.server:6379"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis-commander.rule=Host(`rediscommander.$DOMAIN_NAME`)"
      - "traefik.http.routers.redis-commander.entrypoints=websecure"
      - "traefik.http.services.redis-commander.loadbalancer.server.port=8081"
      - "traefik.http.routers.redis-commander.tls=true"
      - "traefik.http.routers.redis-commander.tls.certresolver=le"
      - "traefik.http.routers.redis-commander.middlewares=redis-commander-auth, redis-commander-compress"
      - "traefik.http.middlewares.redis-commander-auth.basicauth.users=${TRAEFIK_BASIC_USER}:${TRAEFIK_BASIC_PASSWORD_ENCODED}"
      - "traefik.http.middlewares.redis-commander-compress.compress=true"
  website:
    image: haakco/stage3-ubuntu-20.04-php7.4-lv-wave
    container_name: "web"
    hostname: web.server
    restart: always
    labels:
      - "com.ouroboros.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`$DOMAIN_NAME`,`www.$DOMAIN_NAME`)"
      - "traefik.http.routers.website.entrypoints=websecure"
      - "traefik.http.routers.website.tls=true"
      - "traefik.http.routers.website.tls.certresolver=le"
      - "traefik.http.routers.website.middlewares=website-compress"
      - "traefik.http.middlewares.website-compress.compress=true"
    environment:
      - GEN_LV_ENV=TRUE
      - LVENV_APP_NAME=HaakCo Wave
      - LVENV_APP_ENV=production
      - LVENV_APP_KEY=$APP_KEY
      - LVENV_APP_DEBUG=true
      - LVENV_APP_LOG_LEVEL=info
      - LVENV_APP_URL=https://$DOMAIN_NAME
      - LVENV_DB_CONNECTION=pgsql
      - LVENV_DB_HOST=postgres
      - LVENV_DB_PORT=5432
      - LVENV_DB_DATABASE=$DB_NAME
      - LVENV_DB_USERNAME=$DB_USER
      - LVENV_DB_PASSWORD=$DB_PASS
      - LVENV_BROADCAST_DRIVER=log
      - LVENV_CACHE_DRIVER=redis
      - LVENV_SESSION_DRIVER=redis
      - LVENV_SESSION_LIFETIME=9999
      - LVENV_QUEUE_DRIVER=redis
      - LVENV_REDIS_HOST=redis.server
      - LVENV_REDIS_PASSWORD=null
      - LVENV_REDIS_PORT=6379
      - LVENV_MAIL_DRIVER=smtp
      - LVENV_MAIL_HOST=smtp.mailtrap.io
      - LVENV_MAIL_PORT=2525
      - LVENV_MAIL_USERNAME=
      - LVENV_MAIL_PASSWORD=
      - LVENV_MAIL_ENCRYPTION=null
      - LVENV_PUSHER_APP_ID=
      - LVENV_PUSHER_APP_KEY=
      - LVENV_PUSHER_APP_SECRET=
      - LVENV_REDIS_CLIENT=phpredis
      - LVENV_JWT_SECRET=$JWT_SECRET
      - LVENV_PADDLE_VENDOR_ID=
      - LVENV_PADDLE_VENDOR_AUTH_CODE=
      - LVENV_PADDLE_ENV=sandbox
      - LVENV_WAVE_DOCS=true
      - LVENV_WAVE_DEMO=true
      - LVENV_WAVE_BAR=true
      - LVENV_TRUSTED_PROXIES=$TRUSTED_PROXIES
      - LVENV_ASSET_URL=' '
